spring.application.name=petvida

spring.datasource.url=jdbc:h2:mem:petvida
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

logging.level.web=trace
spring.thymeleaf.cache=false
